import 'dart:convert';
import 'package:intl/intl.dart';
import 'activity_model.dart';

/// Enum representing the progression lifecycle of a travel plan.
enum TripStatus {
  upcoming,
  active,
  past;

  /// Parses a string representation into a [TripStatus], defaulting to [upcoming].
  static TripStatus fromString(String? value) {
    if (value == null) return TripStatus.upcoming;
    final clean = value.trim().toUpperCase();
    switch (clean) {
      case 'ACTIVE':
        return TripStatus.active;
      case 'PAST':
      case 'COMPLETED':
        return TripStatus.past;
      case 'UPCOMING':
      default:
        return TripStatus.upcoming;
    }
  }

  /// Converts the enum to database code string.
  String toCode() {
    switch (this) {
      case TripStatus.upcoming:
        return 'UPCOMING';
      case TripStatus.active:
        return 'ACTIVE';
      case TripStatus.past:
        return 'PAST';
    }
  }

  /// Human-readable label for UI chips and tabs.
  String get displayName {
    switch (this) {
      case TripStatus.upcoming:
        return 'Upcoming';
      case TripStatus.active:
        return 'Active';
      case TripStatus.past:
        return 'Past';
    }
  }
}

/// Represents a planned travel journey generated by the AI or user.
///
/// Contains high-level itinerary metadata (title, dates, destination, original prompt),
/// tracking status ('UPCOMING', 'ACTIVE', 'PAST'), and an optional collection of
/// associated [ActivityModel] items.
class TripModel {
  /// Unique identifier (UUID or database key) for this trip.
  final String id;

  /// Human-readable name of the trip (e.g., "Paris Art & Culture Getaway").
  final String title;

  /// The original natural language prompt provided by the user.
  final String originalPrompt;

  /// Associated destination identifier (e.g. 'paris' or UUID).
  final String? destinationId;

  /// Display name of the destination city or region (e.g. "Paris", "Tokyo").
  final String? destinationName;

  /// First day of the planned trip.
  final DateTime startDate;

  /// Final day of the planned trip.
  final DateTime endDate;

  /// Timestamp when this trip record was first generated.
  final DateTime createdAt;

  /// Current trip lifecycle status ('UPCOMING', 'ACTIVE', 'PAST').
  /// Kept mutable as [String] for full compatibility with existing code.
  String status;

  /// Estimated overall budget for the trip in standard currency.
  final double? estimatedBudget;

  /// Hero / cover banner image URL for cards and detail headers.
  final String? coverImageUrl;

  /// Optional in-memory list of scheduled activities for this trip.
  final List<ActivityModel> activities;

  /// Raw JSON string returned by the LLM (or fallback engine).
  final String? rawJsonResponse;

  /// Name of the LLM model used (e.g. 'gemini-1.5-flash').
  final String? llmModel;

  /// Flag indicating if generated via live Gemini API call or local fallback.
  final bool isLiveAi;

  /// Latency in milliseconds for LLM round-trip.
  final int latencyMs;

  /// Optional user identifier who owns this trip (for user isolation).
  final String? userId;

  TripModel({
    required this.id,
    this.userId,
    required this.title,
    required this.originalPrompt,
    this.destinationId,
    this.destinationName,
    required this.startDate,
    required this.endDate,
    required this.createdAt,
    this.status = 'UPCOMING',
    this.estimatedBudget,
    this.coverImageUrl,
    this.activities = const [],
    this.rawJsonResponse,
    this.llmModel,
    this.isLiveAi = false,
    this.latencyMs = 0,
  });

  // --------------------------------------------------------------------------
  // Computed Getters & Helpers
  // --------------------------------------------------------------------------

  /// Strongly-typed enum representation of [status].
  TripStatus get statusEnum => TripStatus.fromString(status);

  /// Helper to update status using strongly-typed enum.
  void setStatusFromEnum(TripStatus newStatus) {
    status = newStatus.toCode();
  }

  /// Total duration of the trip in days (inclusive of start and end day).
  int get durationInDays {
    final diff = endDate.difference(startDate).inDays;
    return diff >= 0 ? diff + 1 : 1;
  }

  /// Alias for durationInDays
  int get durationDays => durationInDays;

  /// Convenience status checks
  bool get isUpcoming => status.toUpperCase() == 'UPCOMING';
  bool get isActive => status.toUpperCase() == 'ACTIVE';
  bool get isPast => status.toUpperCase() == 'PAST';

  /// Sum of all costs from loaded activities.
  double get totalActivitiesCost =>
      activities.fold(0.0, (sum, item) => sum + item.cost);

  /// Nicely formatted date range (e.g., "Oct 12 - Oct 15, 2026").
  String get formattedDateRange {
    final startFmt = DateFormat('MMM d').format(startDate);
    final endFmt = DateFormat('MMM d, yyyy').format(endDate);
    return '$startFmt - $endFmt';
  }

  // --------------------------------------------------------------------------
  // Immutability: copyWith
  // --------------------------------------------------------------------------

  /// Creates a copy of this [TripModel] with updated fields.
  TripModel copyWith({
    String? id,
    String? userId,
    String? title,
    String? originalPrompt,
    String? destinationId,
    String? destinationName,
    DateTime? startDate,
    DateTime? endDate,
    DateTime? createdAt,
    String? status,
    double? estimatedBudget,
    String? coverImageUrl,
    List<ActivityModel>? activities,
    String? rawJsonResponse,
    String? llmModel,
    bool? isLiveAi,
    int? latencyMs,
  }) {
    return TripModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      title: title ?? this.title,
      originalPrompt: originalPrompt ?? this.originalPrompt,
      destinationId: destinationId ?? this.destinationId,
      destinationName: destinationName ?? this.destinationName,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      createdAt: createdAt ?? this.createdAt,
      status: status ?? this.status,
      estimatedBudget: estimatedBudget ?? this.estimatedBudget,
      coverImageUrl: coverImageUrl ?? this.coverImageUrl,
      activities: activities ?? this.activities,
      rawJsonResponse: rawJsonResponse ?? this.rawJsonResponse,
      llmModel: llmModel ?? this.llmModel,
      isLiveAi: isLiveAi ?? this.isLiveAi,
      latencyMs: latencyMs ?? this.latencyMs,
    );
  }

  // --------------------------------------------------------------------------
  // Serialization (SQLite & REST / LLM JSON)
  // --------------------------------------------------------------------------

  /// Converts this [TripModel] to a [Map] for SQLite storage or JSON encoding.
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'user_id': userId,
      'title': title,
      'original_prompt': originalPrompt,
      'destination_id': destinationId,
      'destination_name': destinationName,
      'start_date': startDate.toIso8601String(),
      'end_date': endDate.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
      'status': status,
      'estimated_budget': estimatedBudget,
      'cover_image_url': coverImageUrl,
      'raw_json_response': rawJsonResponse,
      'llm_model': llmModel,
      'is_live_ai': isLiveAi ? 1 : 0,
      'latency_ms': latencyMs,
    };
  }

  /// Creates a [TripModel] from a [Map] (from SQLite query or API response).
  factory TripModel.fromMap(Map<String, dynamic> map, {List<ActivityModel> activities = const []}) {
    return TripModel(
      id: (map['id'] ?? '') as String,
      userId: (map['user_id'] ?? map['userId']) as String?,
      title: (map['title'] ?? '') as String,
      originalPrompt: (map['original_prompt'] ?? map['originalPrompt'] ?? '') as String,
      destinationId: (map['destination_id'] ?? map['destinationId']) as String?,
      destinationName: (map['destination_name'] ?? map['destinationName']) as String?,
      startDate: map['start_date'] != null
          ? DateTime.parse(map['start_date'] as String)
          : (map['startDate'] is DateTime
              ? map['startDate'] as DateTime
              : DateTime.now()),
      endDate: map['end_date'] != null
          ? DateTime.parse(map['end_date'] as String)
          : (map['endDate'] is DateTime
              ? map['endDate'] as DateTime
              : DateTime.now().add(const Duration(days: 3))),
      createdAt: map['created_at'] != null
          ? DateTime.parse(map['created_at'] as String)
          : (map['createdAt'] is DateTime
              ? map['createdAt'] as DateTime
              : DateTime.now()),
      status: (map['status'] ?? 'UPCOMING') as String,
      estimatedBudget: map['estimated_budget'] != null
          ? ((map['estimated_budget']) as num).toDouble()
          : (map['estimatedBudget'] != null
              ? ((map['estimatedBudget']) as num).toDouble()
              : null),
      coverImageUrl: (map['cover_image_url'] ?? map['coverImageUrl']) as String?,
      activities: activities,
      rawJsonResponse: (map['raw_json_response'] ?? map['rawJsonResponse']) as String?,
      llmModel: (map['llm_model'] ?? map['llmModel']) as String?,
      isLiveAi: (map['is_live_ai'] == 1 || map['is_live_ai'] == true || map['isLiveAi'] == true),
      latencyMs: (map['latency_ms'] ?? map['latencyMs'] ?? 0) as int,
    );
  }

  /// Serializes directly to a JSON string.
  String toJson() => jsonEncode(toMap());

  /// Deserializes directly from a JSON string.
  factory TripModel.fromJson(String source) =>
      TripModel.fromMap(jsonDecode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return 'TripModel(id: $id, title: $title, status: $status, days: $durationInDays)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is TripModel && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}
